// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: temporal/workflows.proto

package temporal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	common "order-sample/internal/protobuf/common"
	orders "order-sample/internal/protobuf/orders"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowSignal int32

const (
	WorkflowSignal_WORKFLOW_SIGNAL_UNSPECIFIED             WorkflowSignal = 0
	WorkflowSignal_WORKFLOW_SIGNAL_CANCEL_ORDER            WorkflowSignal = 1
	WorkflowSignal_WORKFLOW_SIGNAL_CONFIRM_ORDER           WorkflowSignal = 2
	WorkflowSignal_WORKFLOW_SIGNAL_ORDER_DELIVERY_COMPLETE WorkflowSignal = 3
)

// Enum value maps for WorkflowSignal.
var (
	WorkflowSignal_name = map[int32]string{
		0: "WORKFLOW_SIGNAL_UNSPECIFIED",
		1: "WORKFLOW_SIGNAL_CANCEL_ORDER",
		2: "WORKFLOW_SIGNAL_CONFIRM_ORDER",
		3: "WORKFLOW_SIGNAL_ORDER_DELIVERY_COMPLETE",
	}
	WorkflowSignal_value = map[string]int32{
		"WORKFLOW_SIGNAL_UNSPECIFIED":             0,
		"WORKFLOW_SIGNAL_CANCEL_ORDER":            1,
		"WORKFLOW_SIGNAL_CONFIRM_ORDER":           2,
		"WORKFLOW_SIGNAL_ORDER_DELIVERY_COMPLETE": 3,
	}
)

func (x WorkflowSignal) Enum() *WorkflowSignal {
	p := new(WorkflowSignal)
	*p = x
	return p
}

func (x WorkflowSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_workflows_proto_enumTypes[0].Descriptor()
}

func (WorkflowSignal) Type() protoreflect.EnumType {
	return &file_temporal_workflows_proto_enumTypes[0]
}

func (x WorkflowSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowSignal.Descriptor instead.
func (WorkflowSignal) EnumDescriptor() ([]byte, []int) {
	return file_temporal_workflows_proto_rawDescGZIP(), []int{0}
}

type WorkflowOrderDeliveryCompleteSignal_DeliveryStatus int32

const (
	WorkflowOrderDeliveryCompleteSignal_DELIVERY_STATUS_UNSPECIFIED WorkflowOrderDeliveryCompleteSignal_DeliveryStatus = 0
	WorkflowOrderDeliveryCompleteSignal_DELIVERY_STATUS_SUCCEEDED   WorkflowOrderDeliveryCompleteSignal_DeliveryStatus = 1
	WorkflowOrderDeliveryCompleteSignal_DELIVERY_STATUS_FAILED      WorkflowOrderDeliveryCompleteSignal_DeliveryStatus = 2
)

// Enum value maps for WorkflowOrderDeliveryCompleteSignal_DeliveryStatus.
var (
	WorkflowOrderDeliveryCompleteSignal_DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_SUCCEEDED",
		2: "DELIVERY_STATUS_FAILED",
	}
	WorkflowOrderDeliveryCompleteSignal_DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_SUCCEEDED":   1,
		"DELIVERY_STATUS_FAILED":      2,
	}
)

func (x WorkflowOrderDeliveryCompleteSignal_DeliveryStatus) Enum() *WorkflowOrderDeliveryCompleteSignal_DeliveryStatus {
	p := new(WorkflowOrderDeliveryCompleteSignal_DeliveryStatus)
	*p = x
	return p
}

func (x WorkflowOrderDeliveryCompleteSignal_DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowOrderDeliveryCompleteSignal_DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_workflows_proto_enumTypes[1].Descriptor()
}

func (WorkflowOrderDeliveryCompleteSignal_DeliveryStatus) Type() protoreflect.EnumType {
	return &file_temporal_workflows_proto_enumTypes[1]
}

func (x WorkflowOrderDeliveryCompleteSignal_DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowOrderDeliveryCompleteSignal_DeliveryStatus.Descriptor instead.
func (WorkflowOrderDeliveryCompleteSignal_DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_temporal_workflows_proto_rawDescGZIP(), []int{3, 0}
}

type WorkflowOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string        `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId  string        `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset   *orders.Asset `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Price   *common.Money `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *WorkflowOrderRequest) Reset() {
	*x = WorkflowOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporal_workflows_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOrderRequest) ProtoMessage() {}

func (x *WorkflowOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_workflows_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOrderRequest.ProtoReflect.Descriptor instead.
func (*WorkflowOrderRequest) Descriptor() ([]byte, []int) {
	return file_temporal_workflows_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *WorkflowOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WorkflowOrderRequest) GetAsset() *orders.Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *WorkflowOrderRequest) GetPrice() *common.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

type WorkflowConfirmOrderSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId         string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentOptionId string `protobuf:"bytes,2,opt,name=payment_option_id,json=paymentOptionId,proto3" json:"payment_option_id,omitempty"`
}

func (x *WorkflowConfirmOrderSignal) Reset() {
	*x = WorkflowConfirmOrderSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporal_workflows_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowConfirmOrderSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowConfirmOrderSignal) ProtoMessage() {}

func (x *WorkflowConfirmOrderSignal) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_workflows_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowConfirmOrderSignal.ProtoReflect.Descriptor instead.
func (*WorkflowConfirmOrderSignal) Descriptor() ([]byte, []int) {
	return file_temporal_workflows_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowConfirmOrderSignal) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *WorkflowConfirmOrderSignal) GetPaymentOptionId() string {
	if x != nil {
		return x.PaymentOptionId
	}
	return ""
}

type WorkflowCancelOrderSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *WorkflowCancelOrderSignal) Reset() {
	*x = WorkflowCancelOrderSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporal_workflows_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowCancelOrderSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowCancelOrderSignal) ProtoMessage() {}

func (x *WorkflowCancelOrderSignal) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_workflows_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowCancelOrderSignal.ProtoReflect.Descriptor instead.
func (*WorkflowCancelOrderSignal) Descriptor() ([]byte, []int) {
	return file_temporal_workflows_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowCancelOrderSignal) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type WorkflowOrderDeliveryCompleteSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId       string                                             `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        WorkflowOrderDeliveryCompleteSignal_DeliveryStatus `protobuf:"varint,2,opt,name=status,proto3,enum=workflows.WorkflowOrderDeliveryCompleteSignal_DeliveryStatus" json:"status,omitempty"`
	FailureReason string                                             `protobuf:"bytes,3,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
}

func (x *WorkflowOrderDeliveryCompleteSignal) Reset() {
	*x = WorkflowOrderDeliveryCompleteSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporal_workflows_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowOrderDeliveryCompleteSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOrderDeliveryCompleteSignal) ProtoMessage() {}

func (x *WorkflowOrderDeliveryCompleteSignal) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_workflows_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOrderDeliveryCompleteSignal.ProtoReflect.Descriptor instead.
func (*WorkflowOrderDeliveryCompleteSignal) Descriptor() ([]byte, []int) {
	return file_temporal_workflows_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowOrderDeliveryCompleteSignal) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *WorkflowOrderDeliveryCompleteSignal) GetStatus() WorkflowOrderDeliveryCompleteSignal_DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowOrderDeliveryCompleteSignal_DELIVERY_STATUS_UNSPECIFIED
}

func (x *WorkflowOrderDeliveryCompleteSignal) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

var File_temporal_workflows_proto protoreflect.FileDescriptor

var file_temporal_workflows_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x93, 0x01, 0x0a, 0x14, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x05,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x05, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x12, 0x22, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x63, 0x0a, 0x1a, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a,
	0x0a, 0x11, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x19, 0x57, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x22, 0xac, 0x02, 0x0a, 0x23, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x55, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3d, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x73, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0x6c, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52,
	0x59, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45,
	0x52, 0x59, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x45,
	0x44, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52,
	0x59, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10,
	0x02, 0x2a, 0xa3, 0x01, 0x0a, 0x0e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x1b, 0x57, 0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57,
	0x5f, 0x53, 0x49, 0x47, 0x4e, 0x41, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x57, 0x4f, 0x52, 0x4b, 0x46, 0x4c, 0x4f,
	0x57, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x41, 0x4c, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x5f,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x10, 0x01, 0x12, 0x21, 0x0a, 0x1d, 0x57, 0x4f, 0x52, 0x4b, 0x46,
	0x4c, 0x4f, 0x57, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x41, 0x4c, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49,
	0x52, 0x4d, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x10, 0x02, 0x12, 0x2b, 0x0a, 0x27, 0x57, 0x4f,
	0x52, 0x4b, 0x46, 0x4c, 0x4f, 0x57, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x41, 0x4c, 0x5f, 0x4f, 0x52,
	0x44, 0x45, 0x52, 0x5f, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x43, 0x4f, 0x4d,
	0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x42, 0x8c, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x42, 0x0e, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2d, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x65, 0x6d, 0x70,
	0x6f, 0x72, 0x61, 0x6c, 0xa2, 0x02, 0x03, 0x57, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x57, 0x6f, 0x72,
	0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0xca, 0x02, 0x09, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x73, 0xe2, 0x02, 0x15, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x57, 0x6f, 0x72,
	0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_temporal_workflows_proto_rawDescOnce sync.Once
	file_temporal_workflows_proto_rawDescData = file_temporal_workflows_proto_rawDesc
)

func file_temporal_workflows_proto_rawDescGZIP() []byte {
	file_temporal_workflows_proto_rawDescOnce.Do(func() {
		file_temporal_workflows_proto_rawDescData = protoimpl.X.CompressGZIP(file_temporal_workflows_proto_rawDescData)
	})
	return file_temporal_workflows_proto_rawDescData
}

var file_temporal_workflows_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_temporal_workflows_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_temporal_workflows_proto_goTypes = []interface{}{
	(WorkflowSignal)(0), // 0: workflows.WorkflowSignal
	(WorkflowOrderDeliveryCompleteSignal_DeliveryStatus)(0), // 1: workflows.WorkflowOrderDeliveryCompleteSignal.DeliveryStatus
	(*WorkflowOrderRequest)(nil),                            // 2: workflows.WorkflowOrderRequest
	(*WorkflowConfirmOrderSignal)(nil),                      // 3: workflows.WorkflowConfirmOrderSignal
	(*WorkflowCancelOrderSignal)(nil),                       // 4: workflows.WorkflowCancelOrderSignal
	(*WorkflowOrderDeliveryCompleteSignal)(nil),             // 5: workflows.WorkflowOrderDeliveryCompleteSignal
	(*orders.Asset)(nil),                                    // 6: orders.Asset
	(*common.Money)(nil),                                    // 7: money.Money
}
var file_temporal_workflows_proto_depIdxs = []int32{
	6, // 0: workflows.WorkflowOrderRequest.asset:type_name -> orders.Asset
	7, // 1: workflows.WorkflowOrderRequest.price:type_name -> money.Money
	1, // 2: workflows.WorkflowOrderDeliveryCompleteSignal.status:type_name -> workflows.WorkflowOrderDeliveryCompleteSignal.DeliveryStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_temporal_workflows_proto_init() }
func file_temporal_workflows_proto_init() {
	if File_temporal_workflows_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_temporal_workflows_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporal_workflows_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowConfirmOrderSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporal_workflows_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowCancelOrderSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporal_workflows_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowOrderDeliveryCompleteSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_temporal_workflows_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_workflows_proto_goTypes,
		DependencyIndexes: file_temporal_workflows_proto_depIdxs,
		EnumInfos:         file_temporal_workflows_proto_enumTypes,
		MessageInfos:      file_temporal_workflows_proto_msgTypes,
	}.Build()
	File_temporal_workflows_proto = out.File
	file_temporal_workflows_proto_rawDesc = nil
	file_temporal_workflows_proto_goTypes = nil
	file_temporal_workflows_proto_depIdxs = nil
}
