version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    network_mode: "host"

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper
    env_file:
      - docker-kafka.env
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9091,PLAINTEXT_HOST://localhost:29091
      KAFKA_BROKER_ID: 1
    network_mode: "host"
    restart: unless-stopped
